admins/urls.py
from django.conf.urls import url
from . import views as ind_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$',ind_views.logins, name='login'),
    url(r'^home/$',ind_views.home, name='home'),
     url(r'^logout/$', auth_views.LogoutView.as_view(next_page='admins:login'), name='logout'),
    url(r'^upload/product/$',ind_views.uploadProduct, name='uploadproduct'),
    url(r'^View/Ratings/$',ind_views.viewratings, name='viewratings'),
    url(r'^Ordered/Products/$',ind_views.orderedproducts, name='orderedproducts'),
    url(r'^Confirmed/Products/$',ind_views.confirmedproduct, name='confirmedproduct'),
    url(r'^Graphs/(?:(?P<chart_type>.+))?/$',ind_views.graph, name='graph'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

productreview/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from user.urls import urlpatterns as user_urls
from admins.urls import urlpatterns as admins_urls
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include((user_urls, 'users'), namespace='users')),
    path('admins/', include((admins_urls, 'admins'), namespace='admins')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from . import views as ind_views
from .forms import CustomAuthForm

app_name = 'users'  # Namespace for reverse URL lookups

urlpatterns = [
    # Home page
    path('home/', ind_views.home, name='home'),
    
    # Authentication URLs
    path('', auth_views.LoginView.as_view(
        template_name='login.html',
        authentication_form=CustomAuthForm
    ), name='login'),
    
    path('logout/', auth_views.LogoutView.as_view(next_page='users:login'), name='logout'),
    path('registration/', ind_views.registration, name='registration'),
    
    # Order-related URLs
    path('your-orders/', ind_views.yourorders, name='yourorders'),
    path('confirmed-orders/', ind_views.confirmproducts, name='confirmedorders'),
    path('chechouts/', ind_views.chechouts, name='chechouts'),
    
    # Product-related URLs
    re_path(r'^view-ratings/(?P<pk>\d+)/$', ind_views.viewratings, name='viewratings'),
    path('product-list/', ind_views.productlist, name='productlist'),
    path('top-products/', ind_views.topproducts, name='topproducts'),
    
    # Miscellaneous
    path('graphs/', ind_views.graphs, name='graphs'),
]

assets/templates/admins/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" >

<head>
  <meta charset="UTF-8">
  <title>CSS3 MENU BUILD</title>
  
  
  
      <link rel="stylesheet" href="{% static 'css/style.css' %}">

  
</head>

<body style="background:url({% static 'images/we.jpg' %});">

      <ul>
        <li style="width: 16.6666666666667%"><a href="{% url 'admins:home' %}" target="">Home</a></li>

        <li style="width: 16.6666666666667%"><a href="{% url 'admins:uploadproduct' %}" target="">Upload Products</a></li>

        <li style="width: 16.6666666666667%"><a href="{% url 'admins:viewratings' %}" target="">View Ratings</a></li>

        <li style="width: 16.6666666666667%"><a href="{% url 'admins:orderedproducts' %}" target="">Ordered Products</a></li>

        <li style="width: 16.6666666666667%"><a href="{% url 'admins:confirmedproduct' %}" target="">Confirmed Orders</a></li>
        
        <li style="width: 16.6666666666667%"><a href="{% url 'admins:graph' 'products' %}" target="">Graphs</a></li>

        <li style="width: 16.6666666666667%"><a href="{% url 'admins:logout' %}" target="">Logout</a></li>
    </ul>
  <div style="margin-top:-400px;margin-left:400px;">
    {% block adminbody %}
    {% endblock %}
    </div>

</body>

</html>

assets/templates/admins/confirmedproduct.html
{% extends 'admins/base.html' %}
{% block adminbody %}
<style>
th span{
color:black;
}
span{
color:white;
}
table tr th{
padding:15px;
text-align:center;
}
td{
text-align:center;
}
.tableholder{
padding:10px;
float:left;
width:80%;
background:rgba(94, 142, 137,0.7);
}
table{
border:1px solid green;
border-collapse:collapse;
width:100%;
}
td{
border-right:1px solid green;
border-bottom:1px solid green;
}
tr:first-child{
background:green;
}
</style>
<div class="tableholder">
<table>
  <tr>
    <th><span>Product Name</span></th>
    <th><span>Quantity</span></th>
    <th><span>location</span></th>
    <th><span>Status</span></th>
    <th><span>Date Ordered</span></th>
  </tr>
{% for or in order %}
<tr>
    <td><span>{{or.prod.name}}</span></td>
    <td><span>{{or.prodqty}}</span></td>
    <td><span>{{or.location}}</span></td>
    <td><span>{{or.status}}</span></td>
    <td><span>{{or.dateordered}}</span></td>
{% endfor %}
</tr>
</table>
</div>
{% endblock %}

assets/templates/admins/graph.html
{% extends 'admins/base.html' %}
{% block adminbody %}
<style>
th span{
color:black;
}
span{
color:white;
}
table tr th{
padding:15px;
text-align:center;
}
.tableholder{
padding:10px;
float:left;
width:80%;
background:rgba(94, 142, 137,0.7);
}
table{
width:100%;
border:1px solid green;
border-collapse:collapse;
}
td{
border-right:1px solid green;
border-bottom:1px solid green;
}
tr:first-child{
background:green;
}
.menus{
padding:0px;
margin:0px;
border:1px solid white;
margin-bottom:10px;
}
div.menus a{
color:white;
}
div.menus table tr:first-child{
background:none;
border:none;
}
div.menus table tr td{
background:none;
border:none;
}
</style>

<script>
/*window.onload = function () {

var chart = new CanvasJS.Chart("chartContainer", {
	animationEnabled: true,
	exportEnabled: true,
	title:{
		text: "Product-Wise Ratings Analysis"
	},
	data: [{
		type: "pyramid",
		indexLabelFontSize: 18,
		valueRepresents: "area",
		showInLegend: true,
		legendText: "{indexLabel}",
		toolTipContent: "<b>{indexLabel}:</b> {y}%",
		dataPoints: [
        {% for p in prod %}
            { y: {{p.ratings}}, indexLabel: "{{p.product__name}}" },
        {% endfor %}
			{ y: 30, indexLabel: "Research and Design" },
			{ y: 30, indexLabel: "Manufacturing" },
			{ y: 15, indexLabel: "Marketing" },
			{ y: 13, indexLabel: "Shipping" },
			{ y: 12, indexLabel: "Retail" }
		]
	}]
});
chart.render();

}*/
</script>
<script>
window.onload = function () {

var chart = new CanvasJS.Chart("chartContainer", {
	animationEnabled: true,  
	title:{
		text: "Company Revenue by Year"
	},
	axisY: {
		title: "Revenue in USD",
		valueFormatString: "",
	},
	data: [{
		type: "splineArea",
		color: "rgba(54,158,173,.7)",
		markerSize: 5,
		dataPoints: [
        {% for p in prod %}
			{y: {{p.ratings}} },
        {% endfor %}
			/*{ x: new Date(2000, 0), y: 3289000 },
			{ x: new Date(2001, 0), y: 3830000 },
			{ x: new Date(2002, 0), y: 2009000 },
			{ x: new Date(2003, 0), y: 2840000 },
			{ x: new Date(2004, 0), y: 2396000 },
			{ x: new Date(2005, 0), y: 1613000 },
			{ x: new Date(2006, 0), y: 2821000 },
			{ x: new Date(2007, 0), y: 2000000 },
			{ x: new Date(2008, 0), y: 1397000 },
			{ x: new Date(2009, 0), y: 2506000 },
			{ x: new Date(2010, 0), y: 2798000 },
			{ x: new Date(2011, 0), y: 3386000 },
			{ x: new Date(2012, 0), y: 6704000},
			{ x: new Date(2013, 0), y: 6026000 },
			{ x: new Date(2014, 0), y: 2394000 },
			{ x: new Date(2015, 0), y: 1872000 },
			{ x: new Date(2016, 0), y: 2140000 }*/
		]
	}]
	});
chart.render();

}
</script>

<div class="tableholder">
<div class="menus">
<table>
<tr>
<td style="background:{% if chart_type == 'products' %}green{% endif %}"><a href="{% url 'admins:graph' 'product' %}">Product</a></td>
<td style="background:{% if chart_type == 'category' %}green{% endif %}"><a href="{% url 'admins:graph' 'category' %}">Category</a></td>
<td style="background:{% if chart_type == 'sentiment' %}green{% endif %}"><a href="{% url 'admins:graph' 'sentiment' %}">Sentiment</a></td>
</tr>
</table>
</div>
<div id="chartContainer" style="height: 370px; max-width: 920px; margin: 0px auto;"></div>
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
<table style="margin-top:20px;">
<tr>
<th>X Axis(Products)</th>
<th>Y Axis(Products)</th>
</tr>
{% for p in prod %}
<tr>
	<td>{{p.product__name}}</td>
	<td>{{p.ratings}}</td>
{% endfor %}
</tr>
</table>
</div>
{% endblock %}

assets/templates/admins/graph1.html
{% extends 'admins/base.html' %}
{% block adminbody %}
<style>
th span{
color:black;
}
span{
color:white;
}
table tr th{
padding:15px;
text-align:center;
}
.tableholder{
padding:10px;
float:left;
width:80%;
background:rgba(94, 142, 137,0.7);
}
table{
width:100%;
border:1px solid green;
border-collapse:collapse;
}
td{
border-right:1px solid green;
border-bottom:1px solid green;
}
tr:first-child{
background:green;
}
.menus{
padding:0px;
margin:0px;
border:1px solid white;
margin-bottom:10px;
}
div.menus a{
color:white;
}
div.menus table tr:first-child{
background:none;
border:none;
}
div.menus table tr td{
background:none;
border:none;
}
</style>

<script>
window.onload = function () {

var chart = new CanvasJS.Chart("chartContainer", {
	animationEnabled: true,
	exportEnabled: true,
	title:{
		text: "Category-Wise Ratings Analysis"
	},
	data: [{
		type: "pyramid",
		indexLabelFontSize: 18,
		valueRepresents: "area",
		showInLegend: true,
		legendText: "{indexLabel}",
		toolTipContent: "<b>{indexLabel}:</b> {y}%",
		dataPoints: [
        {% for p in prod %}
            { y: {{p.ratings}}, indexLabel: "{{p.product__category}}" },
        {% endfor %}
/*			{ y: 30, indexLabel: "Research and Design" },
			{ y: 30, indexLabel: "Manufacturing" },
			{ y: 15, indexLabel: "Marketing" },
			{ y: 13, indexLabel: "Shipping" },
			{ y: 12, indexLabel: "Retail" }*/
		]
	}]
});
chart.render();

}
</script>

<div class="tableholder">
<div class="menus">
<table>
<tr>
<td style="background:{% if chart_type == 'products' %}green{% endif %}"><a href="{% url 'admins:graph' 'product' %}">Product</a></td>
<td style="background:{% if chart_type == 'category' %}green{% endif %}"><a href="{% url 'admins:graph' 'category' %}">Category</a></td>
<td style="background:{% if chart_type == 'sentiment' %}green{% endif %}"><a href="{% url 'admins:graph' 'sentiment' %}">Sentiment</a></td>
</tr>
</table>
</div>
<div id="chartContainer" style="height: 370px; max-width: 920px; margin: 0px auto;"></div>
</div>
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
{% endblock %}

assets/templates/admins/graph2.html
{% extends 'admins/base.html' %}
{% block adminbody %}
<style>
th span{
color:black;
}
span{
color:white;
}
table tr th{
padding:15px;
text-align:center;
}
.tableholder{
padding:10px;
float:left;
width:80%;
background:rgba(94, 142, 137,0.7);
}
table{
width:100%;
border:1px solid green;
border-collapse:collapse;
}
td{
border-right:1px solid green;
border-bottom:1px solid green;
}
tr:first-child{
background:green;
}
.menus{
padding:0px;
margin:0px;
border:1px solid white;
margin-bottom:10px;
}
div.menus a{
color:white;
}
div.menus table tr:first-child{
background:none;
border:none;
}
div.menus table tr td{
background:none;
border:none;
}
</style>

<script>
window.onload = function () {

var chart = new CanvasJS.Chart("chartContainer", {
	animationEnabled: true,
	title:{
		text: "Sentiment Based Analysis of User Ratings"
	},	
	axisY: {
		title: "Positive Sentiments",
		titleFontColor: "#4F81BC",
		lineColor: "#4F81BC",
		labelFontColor: "#4F81BC",
		tickColor: "#4F81BC"
	},
	axisY2: {
		title: "Negative Sentiments",
		titleFontColor: "#C0504E",
		lineColor: "#C0504E",
		labelFontColor: "#C0504E",
		tickColor: "#C0504E"
	},	
	toolTip: {
		shared: true
	},
	legend: {
		cursor:"pointer",
		itemclick: toggleDataSeries
	},
	data: [{
		type: "column",
		name: "Positive",
		legendText: "Positive Sentiment",
		showInLegend: true, 
		dataPoints:[
        {% for p in prod %}
			{ label: "{{p.product__name}}", y: {{p.ratings}} },
        {% endfor %}
			/*{ label: "Saudi", y: 266.21 },
			{ label: "Venezuela", y: 302.25 },
			{ label: "Iran", y: 157.20 },
			{ label: "Iraq", y: 148.77 },
			{ label: "Kuwait", y: 101.50 },
			{ label: "UAE", y: 97.8 }*/
		]
	},
	{
		type: "column",	
		name: "Negative",
		legendText: "Negative Sentiment",
		axisYType: "secondary",
		showInLegend: true,
		dataPoints:[
        {% for p in prod1 %}
			{ label: "{{p.product__name}}", y: {{p.ratings}} },
        {% endfor %}
			/*{ label: "Saudi", y: 10.46 },
			{ label: "Venezuela", y: 2.27 },
			{ label: "Iran", y: 3.99 },
			{ label: "Iraq", y: 4.45 },
			{ label: "Kuwait", y: 2.92 },
			{ label: "UAE", y: 3.1 }*/
		]
	}]
});
chart.render();

function toggleDataSeries(e) {
	if (typeof(e.dataSeries.visible) === "undefined" || e.dataSeries.visible) {
		e.dataSeries.visible = false;
	}
	else {
		e.dataSeries.visible = true;
	}
	chart.render();
}

}
</script>

<div class="tableholder">
<div class="menus">
<table>
<tr>
<td style="background:{% if chart_type == 'products' %}green{% endif %}"><a href="{% url 'admins:graph' 'product' %}">Product</a></td>
<td style="background:{% if chart_type == 'category' %}green{% endif %}"><a href="{% url 'admins:graph' 'category' %}">Category</a></td>
<td style="background:{% if chart_type == 'sentiment' %}green{% endif %}"><a href="{% url 'admins:graph' 'sentiment' %}">Sentiment</a></td>
</tr>
</table>
</div>
<div id="chartContainer" style="height: 370px; max-width: 920px; margin: 0px auto;"></div>
</div>
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
{% endblock %}

assets/templates/admins/home.html
{% extends 'admins/base.html' %}
{% block adminbody %}

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style>
.prod{
height:25%;
background:green;
}
.imgdiv{
margin:10px;
background:green;
height:100px;
}
div.imgdiv img{
height:100%;
}
.contentdiv{
position:absolute;
right:10px;
top:10px;
background:red;
}
.tableholder{
padding:10px;
float:left;
width:80%;
background:rgba(94, 142, 137,0.7);
}
table{
width:100%;
}
a:hover{
color:white;
text-decoration:none;
}
a.vewdet{
text-decoration:none;
color:white;
}
a.vewdet:hover{
background:black;
border-radius:50px;
}
th span{
color:black;
}
span{
color:white;
}
table tr th{
padding:15px;
text-align:center;
}
img{
height:100px;
width:100px;
}
</style>
<div class="tableholder">
  <table>
  <tr>
    <th><span>Name</span></th>
    <th><span>Weight</span></th>
    <th><span>Price</span></th>
    <th><span>Image</span></th>
    <th><span>Details</span></th>
  </tr>
{% for pr in prod %}
<tr>
    <td><span>{{pr.name}}</span></td>
    <td><span>{{pr.weight}}</span></td>
    <td><span>{{pr.price}}</span></td>
    <td><img src="{{pr.images.url}}" style="width:200px;"/></td>
    <td><a data-toggle="modal" data-target="#product_view{{pr.id}}" class="vewdet">View Details</a></td>
   
   
   
   
   <div class="modal fade product_view" id="product_view{{pr.id}}">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" style="height:60px;">
                <a href="#" data-dismiss="modal" class="class pull-right"><span class="glyphicon glyphicon-remove" ></span></a>
                <h3 class="modal-title">{{pr.category}}&nbsp;&nbsp;&nbsp;>&nbsp;&nbsp;&nbsp;{{pr.name}}</h3>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6 product_img">
                        <img src="{{pr.images.url}}" class="img-responsive" style="width:490px;height:500px;">
                    </div>
                    <div class="col-md-6 product_content">
                        <h4>Product Id: <span>{{pr.id}}</span></h4>
                        Name&nbsp;&nbsp;&nbsp;:&nbsp;&nbsp;&nbsp;{{pr.name}}<br/><br/>
                        Weight&nbsp;&nbsp;&nbsp;:&nbsp;&nbsp;&nbsp;{{pr.weight}}<br/><br/>
                        color&nbsp;&nbsp;&nbsp;:&nbsp;&nbsp;&nbsp;{{pr.color}}<br/><br/>
                        Price&nbsp;&nbsp;&nbsp;:&nbsp;&nbsp;&nbsp;{{pr.price}}<br/><br/>
                        Category&nbsp;&nbsp;&nbsp;:&nbsp;&nbsp;&nbsp;{{pr.category}}<br/><br/>
                        <span style="color:red;font-size:20px;">stock&nbsp;&nbsp;&nbsp;:&nbsp;&nbsp;&nbsp;{{pr.stock}}</span><br/><br/>
                        Description&nbsp;&nbsp;&nbsp;:&nbsp;&nbsp;&nbsp;{{pr.description}}<br/><br/>
                        <div class="space-ten"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
    
{% endfor %}
 </tr>
    </table>
    </div>
{% endblock %}

assets/templates/admins/login.html
{% extends 'baselog.html' %}
{% block loginbody %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Admin Login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">

    <style>
        * {
            box-sizing: border-box;
        }

        body {
            background: url("{% static 'images/we.jpg' %}") no-repeat center center fixed;
            background-size: cover;
            font-family: 'Poppins', sans-serif;
            margin: 0;
            padding: 0;
            overflow-x: hidden;
            animation: fadeIn 1s ease-in;
        }

        @keyframes fadeIn {
            from { opacity: 0; }
            to { opacity: 1; }
        }

        .mainblog {
            backdrop-filter: blur(15px);
            background: rgba(0, 0, 0, 0.45);
            border-radius: 20px;
            padding: 50px 40px;
            max-width: 400px;
            margin: 10px auto 40px;
            box-shadow: 0 8px 32px rgba(0, 0, 0, 0.6);
            text-align: center;
            color: white;
            border: 1px solid rgba(255, 255, 255, 0.2);
        }

        .mainblog img {
            width: 80px;
            margin-bottom: 20px;
        }

        .logintable {
            width: 100%;
        }

        input[type="text"], input[type="password"] {
            width: 100%;
            padding: 14px;
            margin: 12px 0;
            background: rgba(255, 255, 255, 0.05);
            border: 1px solid rgba(255,255,255,0.3);
            color: white;
            border-radius: 10px;
            font-size: 16px;
            transition: 0.3s ease;
        }

        input[type="text"]:focus,
        input[type="password"]:focus {
            outline: none;
            border-color: #6ee7b7;
            background: rgba(255, 255, 255, 0.1);
        }

        input::placeholder {
            color: white;
            opacity: 0.7;
        }

        input[type="submit"].subbtn {
            width: 70%;
            padding: 12px;
            background: rgba(255, 255, 255, 0.2);
            border: 1px solid white;
            border-radius: 8px;
            color: white;
            font-weight: bold;
            text-transform: uppercase;
            cursor: pointer;
            transition: all 0.3s ease;
            margin-top: 20px;
        }

        input[type="submit"].subbtn:hover {
            background: white;
            color: #2c3e50;
        }

        a {
            color: white;
            text-decoration: none;
            margin: 10px;
            display: inline-block;
            font-weight: 500;
            transition: 0.3s;
        }

        a:hover {
            color: #2c3e50;
            background: white;
            padding: 6px 12px;
            border-radius: 6px;
        }

        .login-options {
            margin-top: 20px;
        }

        .register-link {
            margin-top: 20px;
            display: block;
            font-size: 15px;
        }

        .banner {
            width: 100%;
            background: linear-gradient(135deg, rgba(204, 125, 194, 0.9), rgba(76, 161, 175, 0.9));
            border-top: 1px solid rgba(255,255,255,0.2);
            padding: 10px 0;
            box-shadow: 0 -2px 15px rgba(0,0,0,0.1);
            position: fixed;
            bottom: 0;
            z-index: 1000;
        }

        .marquee-text {
            color: #fff;
            font-size: 20px;
            font-weight: 500;
            text-transform: uppercase;
            margin: 0;
            letter-spacing: 1.2px;
            text-shadow: 1px 1px 2px rgba(0,0,0,0.2);
        }

        .title-img1 {
            width: 80%;
            margin-top: 1%;
            display: block;
            margin-left: auto;
            margin-right: auto;
        }

        .title-img2 {
            width: 40%;
            margin-left: auto;
            margin-right: auto;
            margin-top: -2%;
            display: block;
        }

        @media (max-width: 480px) {
            .mainblog {
                width: 90%;
                padding: 40px 20px;
            }

            .title-img2 {
                width: 80%;
                margin-top: 0;
            }

            .marquee-text {
                font-size: 14px;
            }
        }
    </style>
</head>
<body>

    <!-- Header Images -->
    <img src="{% static 'images/title2.png' %}" class="title-img1">
    <img src="{% static 'images/title1.png' %}" class="title-img2">

    <!-- Login Form -->
    <div class="mainblog">
        <img src="{% static 'images/admin.png' %}" alt="Admin Icon">
        <form method="post" autocomplete="off">
            {% csrf_token %}
            <table class="logintable">
                <tr><td><input type="text" name="username" placeholder="Username" required></td></tr>
                <tr><td><input type="password" name="password" placeholder="Password" required></td></tr>
                <tr><td><input type="submit" value="Submit" class="subbtn" /></td></tr>
            </table>

            <div class="login-options">
                <a href="{% url 'users:login' %}">User Login</a> |
                <a href="{% url 'admins:login' %}">Admin Login</a>
            </div>
            <a href="{% url 'users:registration' %}" class="register-link">New user? Register Here</a>
        </form>
    </div>

    <!-- Marquee Banner -->
    <div class="banner">
        <marquee behavior="scroll" direction="left" scrollamount="6">
            <p class="marquee-text">✦ Weakly-supervised Deep Embedding for Product Review Sentiment Analysis ✦</p>
        </marquee>
    </div>

</body>
</html>
{% endblock %}

assets/templates/admins/orderedproducts.html
{% extends 'admins/base.html' %}
{% block adminbody %}
<style>
tr:first-child{
background:green;
}
th span{
color:black;
}
span{
color:white;
}
table tr th{
padding:15px;
text-align:center;
}
.tableholder{
padding:10px;
float:left;
width:80%;
background:rgba(94, 142, 137,0.7);
}
table{
border:1px solid green;
border-collapse:collapse;
width:100%;
}
td{
border-right:1px solid green;
border-bottom:1px solid green;
}
</style>
<div class="tableholder">
<table>
<tr>
<th><span>Product Name</span></th>
<th><span>Product price(in Rs.)</span></th>
<th><span>Ratings</span></th>
<th><span>Reviews</span></th>
<th><span>Sentiment</span></th>
</tr>
{% for or in order %}
<tr>
    <td align="center"><span>{{or.prod.name}}</span></td>
<td align="center"><span>{{or.prodqty}}</span></td>
<td align="center"><span>{{or.location}}</span></td>
<td align="center"><span>{{or.status}}</span></td>
<td align="center"><span>{{or.dateordered}}</span></td>
{% endfor %}
</tr>
</table>
{% endblock %}

assets/templates/admins/uploadProduct.html
{% extends 'admins/base.html' %}
{% load static %}
{% block adminbody %}

<style>
.uploadprod{
background:rgba(94, 142, 137,0.8);
float:left;
padding:10px;
width:80%;
}
table{
width:30%;
}
tr{
height:60px;
}
td{
align:center;
align:center;
}
input[type=text],input[type=number],input[type=password],input[type=email],select{
width:100%;
background:none;
border:1px solid white;
padding:10px;
color:white;
}
select{
background:none;
color:black;
}
input[type=submit]{
width:50%;
height:40px;
background:none;
border:1px solid white;
text-transform:uppercase;
color:white;
cursor:pointer;
padding:2px;
}
input[type=submit]:hover{
background:white;
color:rgb(94, 142, 137);
font-weight: bold;
}
::placeholder{
color:white;
}
</style>

<div class="uploadprod">
<form method="Post" enctype="multipart/form-data" autocomplete="off">
{% csrf_token %}
<table>
    <tr>
       <td>{{form.name}}</td>
    </tr>
    <tr>
        <td>{{form.weight}}</td>
    </tr>
    <tr>
        <td>{{form.color}}</td>
    </tr>
    <tr>
        <td>{{form.price}}</td>
    </tr>
    <tr>
        <td>{{form.category}}</td>
    </tr>
    <tr>
        <td>{{form.stock}}</td>
    </tr>
    <tr>
        <td>{{form.description}}</td>
    </tr>
    <tr>
        <td>{{form.images}}</td>
    </tr>
    <tr>
        <td align="center"><input type="submit" name="submit" value="submit"></td>
    </tr>
</table>
</form>
<img src="{% static 'images/upload.gif' %}" style="height:200px;position:absolute;right:200px;top:300px;">
</div>
{% endblock %}

assets/templates/admins/viewratings.html
{% extends 'admins/base.html' %}
{% block adminbody %}
<style>
th span{
color:black;
}
span{
color:white;
}
table tr th{
padding:15px;
text-align:center;
}
.tableholder{
padding:10px;
float:left;
width:80%;
background:rgba(94, 142, 137,0.7);
}
table{
width:100%;
border:1px solid green;
border-collapse:collapse;
}
td{
border-right:1px solid green;
border-bottom:1px solid green;
}
tr:first-child{
background:green;
}
</style>
<div class="tableholder">
<table>
<tr>
<th><span>Product Name</span></th>
<th><span>Product price(in Rs.)</span></th>
<th><span>Ratings</span></th>
<th><span>Reviews</span></th>
<th><span>Sentiment</span></th>
</tr>
{% for ra in ratings %}
<tr>
    <td align="center"><span>{{ra.product.name}}</span></td>
    <td align="center"><span>{{ra.product.price}}</span></td>
    <td align="center"><span>{{ra.ratings}}</span></td>
    <td align="center"><span>{{ra.reviews}}</span></td>
    <td align="center"><span>{{ra.sentiments}}</span></td>
{% endfor %}
</tr>
</table>
</div>
{% endblock %}