productreview/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from user.urls import urlpatterns as user_urls
from admins.urls import urlpatterns as admins_urls
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include((user_urls, 'users'), namespace='users')),
    path('admins/', include((admins_urls, 'admins'), namespace='admins')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from . import views as ind_views
from .forms import CustomAuthForm

app_name = 'users'  # Namespace for reverse URL lookups

urlpatterns = [
    # Home page
    path('home/', ind_views.home, name='home'),
    
    # Authentication URLs
    path('', auth_views.LoginView.as_view(
        template_name='login.html',
        authentication_form=CustomAuthForm
    ), name='login'),
    
    path('logout/', auth_views.LogoutView.as_view(next_page='users:login'), name='logout'),
    path('registration/', ind_views.registration, name='registration'),
    
    # Order-related URLs
    path('your-orders/', ind_views.yourorders, name='yourorders'),
    path('confirmed-orders/', ind_views.confirmproducts, name='confirmedorders'),
    path('chechouts/', ind_views.chechouts, name='chechouts'),
    
    # Product-related URLs
    re_path(r'^view-ratings/(?P<pk>\d+)/$', ind_views.viewratings, name='viewratings'),
    path('product-list/', ind_views.productlist, name='productlist'),
    path('top-products/', ind_views.topproducts, name='topproducts'),
    
    # Miscellaneous
    path('graphs/', ind_views.graphs, name='graphs'),
]

assets/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" >

<head>
  <meta charset="UTF-8">
  <title>CSS3 MENU BUILD</title>
      <link rel="stylesheet" href="{% static 'css/style.css' %}">

  
</head>

<body style="background:url({% static 'images/we.jpg' %});">

      <ul>
        <li class="active" style="width: 16.6666666666667%"><a href="{% url 'users:home' %}" target="">Home</a></li>

        <li style="width: 16.6666666666667%"><a href="{% url 'users:yourorders' %}" target="">Your Orders</a></li>

        <li style="width: 16.6666666666667%"><a href="{% url 'users:confirmedorders' %}" target="">Confirmed Products</a></li>

        <li style="width: 16.6666666666667%"><a href="{% url 'users:productlist' %}" target="">Product List</a></li>
        
        <li style="width: 16.6666666666667%"><a href="{% url 'users:topproducts' %}" target="">Top Products</a></li>

        <li style="width: 16.6666666666667%"><a href="{% url 'users:graphs' %}" target="">Graphs</a></li>

        <li style="width: 16.6666666666667%"><a href="{% url 'users:logout' %}" target="">Logout</a></li>
    </ul>
  
  <div style="margin-top:-400px;margin-left:400px;">
    {% block userbody %}
    {% endblock %}
    </div>
    

</body>

</html>

assets/templates/baselog.html
{% load static %}
<!DOCTYPE html>
<html lang="en" >

<head>
  <meta charset="UTF-8">
  <title>CSS3 MENU BUILD</title>
        
</head>

<body style="background:url({% static 'images/we.jpg' %});">

{% block loginbody %}
{% endblock %}

</body>

</html>

assets/templates/confirmed.html
{% extends 'base.html' %}
{% block userbody %}
{% load static %}
<style>

.titlebar
{
padding:10px;
width:97%;
height:80px;
background:rgba(94, 142, 137,0.8);
margin-bottom:20px;
border:2px solid rgb(241, 103, 103);
border-radius:10px;
}
div.titlebar img.usicon{
position:relative;
left:17%;
}
div.titlebar img.caicon{
position:relative;
margin-left:3%;
}
@font-face {
    font-family: Lobster;
    src: url({% static 'fonts/Lobster.otf' %});
}
.para{
text-align:center;
//text-transform:uppercase;
font-size:30px;
width:100%;
float:left;
margin-top:0px;
color:white;
font-family:Lobster;
}
.containersd{
width:100%;
margin-left:-50px;
}
.outercas{
height:100%;
width:100%;
background:rgba(94, 142, 137,0.6);
overflow:auto;
border:2px solid rgb(241, 103, 103);
border-radius:10px;
}
</style>
<div class="containersd">
<div class="titlebar">
<p class="para">Weakly-supervised Deep Embedding for Product Review Sentiment Analysis</p>
</div>
<div class="outercas">
<table>
<tr>
    <th>Product Name</th>
    <th>Image</th>
    <th>Qty</th>
    <th>Location</th>
    <th>Ordered Date</th>
    <th>Status</th>
</tr>
{% for pr in prod %}
<tr>
<td>{{pr.prod.name}}</td>
<td><img src="{{pr.prod.images.url}}" style="width:100px;height:100px;" /></td>
<td>{{pr.prodqty}}</td>
<td>{{pr.location}}</td>
<td>{{pr.dateordered}}</td>
<td>
{{pr.status}}
</td>
{% endfor %}
</tr>
</table>
{% endblock %}

assets/templates/graphs.html
{% extends 'base.html' %}
{% block userbody %}
{% load static %}

<style>

.titlebar
{
padding:10px;
width:95%;
height:80px;
background:rgba(94, 142, 137,0.8);
margin-bottom:20px;
margin-left:-50px;
border:2px solid rgb(241, 103, 103);
border-radius:10px;
}

@font-face {
    font-family: Lobster;
    src: url({% static 'fonts/Lobster.otf' %});
}
.para{
text-align:center;
//text-transform:uppercase;
font-size:30px;
width:100%;
float:left;
margin-top:0px;
color:white;
font-family:Lobster;
}

.outercas{
margin:center;
height:100%;
width:98%;
padding:10px;
background:rgba(94, 142, 137,0.6);
overflow:auto;
border:2px solid rgb(241, 103, 103);
border-radius:10px;
margin-left:-50px;
}

</style>
<script>
window.onload = function () {

var chart = new CanvasJS.Chart("chartContainer", {
	animationEnabled: true,
	title:{
		text: "Products Purchased",
		horizontalAlign: "left"
	},
	data: [{
		type: "doughnut",
		startAngle: 60,
		//innerRadius: 60,
		indexLabelFontSize: 17,
		indexLabel: "{label} - #percent%",
		toolTipContent: "<b>{label}:</b> {y} (#percent%)",
		dataPoints: [
        {% for p in prod %}
			{ y: {{p.ratings}}, label: "{{p.product__name}}" },
			/*{ y: 67, label: "Inbox" },
			{ y: 28, label: "Archives" },
			{ y: 10, label: "Labels" },
			{ y: 7, label: "Drafts"},
			{ y: 15, label: "Trash"},
			{ y: 6, label: "Spam"}*/
        {% endfor %}
		]
	}]
});
chart.render();

}
</script>

<div class="titlebar">
<p class="para">Weakly-supervised Deep Embedding for Product Review Sentiment Analysis</p>
</div>
<div class="outercas">
<div id="chartContainer" style="height: 370px; max-width: 920px; margin: 0px auto;"></div>
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
</div>
{% endblock %}

assets/templates/home.html
{% extends 'base.html' %}
{% block userbody %}
{% load static %}
<style>
.outercas{
height:100%;
width:100%;
background:rgba(94, 142, 137,0.6);
overflow:auto;
border:2px solid rgb(241, 103, 103);
border-radius:10px;
}
.innerclas:hover{
color:white;
background:rgba(94, 142, 137,0.2);
}
.innerclas{
width:15%;
float:left;
padding:10px;
background:white;
margin:10px;
}
.viewprodlink{
padding:0px;
spacing:0px;
}
.intabl{
width:60%;
margin:auto;
}
.intabl1{
width:60%;
margin:auto;
}

table.intabl tr td{
height:40px;
}
table.intabl1 tr td{
height:40px;
}
.dots{
padding-left:20px;
padding-right:20px;
font-weight:bold;
}
.containersd{
width:100%;
margin-left:-50px;
}
.titlebar
{
padding:20px;
width:100%;
height:100px;
background:rgba(94, 142, 137,0.8);
margin-bottom:20px;
border:2px solid rgb(241, 103, 103);
border-radius:10px;
}
div.titlebar img.usicon{
position:relative;
left:17%;
}
div.titlebar img.caicon{
position:relative;
margin-left:3%;
}
@font-face {
    font-family: Lobster;
    src: url({% static 'fonts/Lobster.otf' %});
}
.para{
text-align:center;
//text-transform:uppercase;
font-size:30px;
width:75%;
float:left;
margin-top:-20px;
color:white;
font-family:Lobster;
}

.comico{
float:left;
padding:0px;
margin:0px;
}
input[type=text],input[type=number]{
visibility:block;
}

</style>
<link rel="stylesheet" href="{% static 'css/bootstrap1.min.css' %}">
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>

<div class="containersd">
<div class="titlebar">
<p class="para">Weakly-supervised Deep Embedding for Product Review Sentiment Analysis</p>
<a href="{% url 'users:yourorders' %}" class="comico" style="margin-left:40px;"><img src="{% static 'images/cart.png' %}" style="width:40px;height:40px;"/></a>
</div>
<div class="outercas">
{% for pro in prod %}
<div class="innerclas">
<img src="{{pro.images.url}}" style="width:100%;height:100px"><br/>
{{pro.name}}<br/>
<a class="viewprodlink"  data-toggle="modal" data-target="#myModal{{pro.id}}">view product</a>
</div>
<div class="modal fade" id="myModal{{pro.id}}" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Product Details</h4>
        </div>
        <div class="modal-body">
            <table>
            <tr>
            <td colspan="2"><img src="{{pro.images.url}}" style="height:250px;width:565px;"/></td>
            </tr>
            <tr>
            <td align="center">
                <table class="intabl">
                <tr>
                <td>Name</td>
                <td><span class="dots">:</span></td>
                <td>{{pro.name}}</td>
            </tr>
            <tr>
                <td>weight</td>
                <td><span class="dots">:</span></td>
                <td>{{pro.weight}}</td>
            </tr>
            <tr>
                <td>color</td>
                <td><span class="dots">:</span></td>
                <td>{{pro.color}}</td>
            </tr>
            <tr>
                <td>price</td>
                <td><span class="dots">:</span></td>
                <td>{{pro.price}}</td>
            </tr>
            <tr>
                <td>category</td>
                <td><span class="dots">:</span></td>
                <td>{{pro.category}}</td>
            </tr>
            <tr>
                <td>stock</td>
                <td><span class="dots">:</span></td>
                <td>
                {% if pro.stock > 0 %}
                <span>{{pro.stock}}</span>
                {% else %}
                <span>No Stock</span>
                {% endif %}
                </td>
            </tr>
            <tr>
                <td>description</td>
                <td><span class="dots">:</span></td>
                <td>{{pro.description}}</td>
                </tr>
                </table>
                </td>
            </tr>
            <tr>
               <td>
                    <table  class="intabl1">
                    <tr>
                    <td colspan="3"><div style="width: 100%; height: 20px; border-bottom: 1px solid black; text-align: center">
      <span style="font-size: 25px; background-color: white; padding: 0 10px;">
        Cart Details<!--Padding is optional-->
      </span>
    </div></td>
                    </tr>
                    <tr>
                    <form method="POST" autocomplete="off">
                    {% csrf_token %}
                    <td><span >Product Quantity</span></td>
                    <td><span class="dots">:</span></td>
                    <td>{{ form.prodqty }}</td>
                    </tr>
                    <tr>
                    <td>Location</td>
                    <td><span class="dots">:</span></td>
                    <td>{{ form.location }}</td>
                    </tr>
                    </table>
               </td>
            </tr>
            </table>          
            <input type="hidden" name="idu" value="{{pro.id}}" style="visibility:none">
        </div>
        <div class="modal-footer">
          <button type="submit" name="addcart" class="btn btn-default">Add To Cart</button>
          </form>
          <a class="btn btn-default" href="{% url 'users:viewratings' pro.id %}">View Ratings</a>
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      <script>
      function foo()
      {
        window.location = "{% url 'users:viewratings' pro.id %}";
      }
      </script>
    </div>
  </div>
{% endfor %}
</div>
</div>
{% endblock %}

assets/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">

    <style>
        * {
            box-sizing: border-box;
        }

        body {
            background: url("{% static 'images/we.jpg' %}") no-repeat center center fixed;
            background-size: cover;
            font-family: 'Poppins', sans-serif;
            margin: 0;
            padding: 0;
            overflow-x: hidden;
            animation: fadeIn 1s ease-in;
        }

        @keyframes fadeIn {
            from { opacity: 0; }
            to { opacity: 1; }a
        }

        .mainblog {
            backdrop-filter: blur(15px);
            background: rgba(0, 0, 0, 0.45);
            border-radius: 20px;
            padding: 50px 40px;
            max-width: 400px;
            margin: 10px auto 40px;
            box-shadow: 0 8px 32px rgba(0, 0, 0, 0.6);
            text-align: center;
            color: white;
            border: 1px solid rgba(255, 255, 255, 0.2);
        }

        .mainblog img {
            width: 80px;
            margin-bottom: 20px;
        }

        .logintable {
            width: 100%;
        }

        input[type="text"], input[type="password"] {
            width: 100%;
            padding: 14px;
            margin: 12px 0;
            background: rgba(255, 255, 255, 0.05);
            border: 1px solid rgba(255,255,255,0.3);
            color: white;
            border-radius: 10px;
            font-size: 16px;
            transition: 0.3s ease;
        }

        input[type="text"]:focus,
        input[type="password"]:focus {
            outline: none;
            border-color: #6ee7b7;
            background: rgba(255, 255, 255, 0.1);
        }

        input::placeholder {
            color: white;
            opacity: 0.7;
        }

        input[type="submit"].subbtn {
            width: 70%;
            padding: 12px;
            background: rgba(255, 255, 255, 0.2);
            border: 1px solid white;
            border-radius: 8px;
            color: white;
            font-weight: bold;
            text-transform: uppercase;
            cursor: pointer;
            transition: all 0.3s ease;
            margin-top: 20px;
        }

        input[type="submit"].subbtn:hover {
            background: white;
            color: #2c3e50;
        }

        a {
            color: white;
            text-decoration: none;
            margin: 10px;
            display: inline-block;
            font-weight: 500;
            transition: 0.3s;
        }

        a:hover {
            color: #2c3e50;
            background: white;
            padding: 6px 12px;
            border-radius: 6px;
        }

        .login-options {
            margin-top: 20px;
        }

        .register-link {
            margin-top: 20px;
            display: block;
            font-size: 15px;
        }

        .banner {
            width: 100%;
            background: linear-gradient(135deg, rgba(204, 125, 194, 0.9), rgba(76, 161, 175, 0.9));
            border-top: 1px solid rgba(255,255,255,0.2);
            padding: 10px 0;
            box-shadow: 0 -2px 15px rgba(0,0,0,0.1);
            position: fixed;
            bottom: 0;
            z-index: 1000;
        }

        .marquee-text {
            color: #fff;
            font-size: 20px;
            font-weight: 500;
            text-transform: uppercase;
            margin: 0;
            letter-spacing: 1.2px;
            text-shadow: 1px 1px 2px rgba(0,0,0,0.2);
        }

        .title-img1 {
    width: 80%;         /* decreased from 100% */
    margin-top: 1%;
    display: block;
    margin-left: auto;
    margin-right: auto;
}

.title-img2 {
    width: 40%;         /* decreased from 60% */
    margin-left: auto;
    margin-right: auto;
    margin-top: -2%;
    display: block;
}

        @media (max-width: 480px) {
            .mainblog {
                width: 90%;
                padding: 40px 20px;
            }

            .title-img2 {
                width: 80%;
                margin-top: 0;
            }

            .marquee-text {
                font-size: 14px;
            }
        }
    </style>
</head>
<body>

    <!-- Header Images -->
    <img src="{% static 'images/title2.png' %}" class="title-img1">
    <img src="{% static 'images/title1.png' %}" class="title-img2">

    <!-- Login Form -->
    <div class="mainblog">
        <img src="{% static 'images/user1.png' %}" alt="User Icon">
        <form method="post" autocomplete="off">
            {% csrf_token %}
            <table class="logintable">
                <tr><td>{{ form.username }}</td></tr>
                <tr><td>{{ form.password }}</td></tr>
                <tr><td><input type="submit" value="Login" class="subbtn" /></td></tr>
            </table>

            <div class="login-options">
                <a href="{% url 'users:login' %}">User Login</a> |
                <a href="{% url 'admins:login' %}">Admin Login</a>
            </div>

            <a href="{% url 'users:registration' %}" class="register-link">New user? Register Here</a>
        </form>
    </div>

    <!-- Marquee Banner -->
    <div class="banner">
        <marquee behavior="scroll" direction="left" scrollamount="6">
            <p class="marquee-text">✦ Weakly-supervised Deep Embedding for Product Review Sentiment Analysis ✦</p>
        </marquee>
    </div>

</body>
</html>

assets/templates/productlist.html
{% extends 'base.html' %}
{% block userbody %}
{% load static %}

<style>
.accordion {
    background-color: #eee;
    color: #444;
    cursor: pointer;
    padding: 18px;
    width: 100%;
    border: none;
    text-align: left;
    outline: none;
    font-size: 15px;
    transition: 0.4s;
}

.active, .accordion:hover {
    background-color: #ccc;
}

.accordion:after {
    content: '\002B';
    color: #777;
    font-weight: bold;
    float: right;
    margin-left: 5px;
}


.panel {
    padding:0 18px;
    background-color: white;
    max-height: 0;
    overflow: hidden;
    transition: max-height 0.2s ease-out;
}
table{
    border-collapse:collapse;
    border:1px solid green;
}
td{
border-bottom:1px solid green;
padding:2px;
}
th{
background:green;
}
tr:hover{
background:green;
}
.outercas{
height:100%;
width:70%;
padding:10px;
background:rgba(94, 142, 137,0.6);
overflow:auto;
border:2px solid rgb(241, 103, 103);
border-radius:10px;
}
@font-face {
    font-family: Lobster;
    src: url({% static 'fonts/Lobster.otf'%});
}
.para{
    text-align:center;
    /* text-transform:uppercase; */
    font-size:30px;
    width:95%;
    float:left;
    margin-top:-20px;
    color:white;
    font-family:Lobster;
}
.titlebar
{
padding:20px;
width:80%;
height:40px;
background:rgba(94, 142, 137,0.8);
margin-bottom:20px;
border:2px solid rgb(241, 103, 103);
border-radius:10px;
}
</style>
</head>
<body>
<div class="titlebar">
<p class="para">Weakly-supervised Deep Embedding for Product Review Sentiment Analysis</p>
</div>
<div class="outercas">
<table>
<tr>
<th>Id</th>
<th>Name</th>
<th>Weight</th>
</tr>
    {% for pr in prod %}
            <tr>
            <td><span style="color:white;">{{forloop.counter}}</span></td>
            <td><span style="color:white;">{{pr.product__name}}</span></td>
            <td><span style="color:white;">{{pr.rati}}</span></td>
    {% endfor %}
        </tr>
    </table>
</div>
{% endblock %}

assets/templates/topproducts.html
{% extends 'base.html' %}
{% block userbody %}
{% load static %}

<style>
.accordion {
    background-color: #eee;
    color: #444;
    cursor: pointer;
    padding: 18px;
    width: 100%;
    border: none;
    text-align: left;
    outline: none;
    font-size: 15px;
    transition: 0.4s;
}

.active, .accordion:hover {
    background-color: #ccc;
}

.accordion:after {
    content: '\002B';
    color: #777;
    font-weight: bold;
    float: right;
    margin-left: 5px;
}


.panel {
    padding:0 18px;
    background-color: white;
    max-height: 0;
    overflow: hidden;
    transition: max-height 0.2s ease-out;
}
table{
border-collapse:collapse;
border:1px solid green;
}
td{
border-bottom:1px solid green;
padding:2px;
}
th{
background:green;
}
tr:hover{
background:#CCCCCC;
}
</style>
</head>
<body>

{% for val in vallit %}
<button class="accordion">{{val.category}}</button>
<div class="panel">
<table>
<tr>
<th>Name</th>
<th>Weight</th>
<th>Color</th>
<th>Price</th>
<th>Stock</th>
<th>Image</th>
<th>Description</th>
</tr>
    {% for pr in prod %}
        {% if pr.category == val.category %}
            <tr>
            <td>{{pr.name}}</td>
            <td>{{pr.weight}}</td>
            <td>{{pr.color}}</td>
            <td>{{pr.price}}</td>
            <td>{{pr.stock}}</td>
            <td><img src="{{pr.images.url}}" style="width:100px;height:100px;" /></td>
            <td>{{pr.description}}</td>
        {% endif %}
    {% endfor %}
        </tr>
    </table>
</div>
{% endfor %}

<script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.maxHeight){
      panel.style.maxHeight = null;
    } else {
      panel.style.maxHeight = panel.scrollHeight + "px";
    } 
  });
}
</script>


{% endblock %}

assets/templates/yourorders.html
{% extends 'base.html' %}
{% block userbody %}
{% load static %}
<style>

.titlebar
{
padding:20px;
width:100%;
height:100px;
background:rgba(94, 142, 137,0.8);
margin-bottom:20px;
border:2px solid rgb(241, 103, 103);
border-radius:10px;
}
div.titlebar img.usicon{
position:relative;
left:17%;
}
div.titlebar img.caicon{
position:relative;
margin-left:3%;
}
@font-face {
    font-family: Lobster;
    src: url({% static 'fonts/Lobster.otf' %});
}
.para{
text-align:center;
//text-transform:uppercase;
font-size:30px;
width:75%;
float:left;
margin-top:-20px;
color:white;
font-family:Lobster;
}
.containersd{
width:100%;
margin-left:-50px;
}
.outercas{
height:100%;
width:100%;
background:rgba(94, 142, 137,0.6);
overflow:auto;
border:2px solid rgb(241, 103, 103);
border-radius:10px;
}
</style>
<link rel="stylesheet" href="{% static 'css/bootstrap1.min.css' %}">
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
<div class="containersd">
<div class="titlebar">
<p class="para">Weakly-supervised Deep Embedding for Product Review Sentiment Analysis</p>
<a href="{% url 'users:chechouts' %}" class="comico" style="margin-left:40px;margin-top:-40px;"><img src="{% static 'images/checkout.png' %}" style="width:80px;height:80px;"/></a>
</div>
<div class="outercas">
<table>
<tr>
    <th>Product Name</th>
    <th>Image</th>
    <th>Qty</th>
    <th>Location</th>
    <th>Ordered Date</th>
    <th colspan="2">Update / Cancel</th>
</tr>
{% for pr in pror %}
<tr>
<td>{{pr.prod.name}}</td>
<td><img src="{{pr.prod.images.url}}" style="width:100px;height:100px;" /></td>
<td>{{pr.prodqty}}</td>
<td>{{pr.location}}</td>
<td>{{pr.dateordered}}</td>
<td><a class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal{{pr.id}}">Update</a></td>
<td>
<form method="POST" autocomplete="off">
{% csrf_token %}
<input type="hidden" name="idys" value="{{pr.id}}">
<button type="submit" name="cancel"  class="btn btn-info btn-lg">Cancel</button></td>
</form>
 <div class="modal fade" id="myModal{{pr.id}}" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Modal Header</h4>
        </div>
        <div class="modal-body">
          
          
          
          
       <img src="{{pr.prod.images.url}}"  style="height:250px;width:565px;"><br/>
          {{pr.prod.name}}<br/>
          {{pr.prod.price}}<br/>
          {{pr.prod.category}}<br/>
          {{pr.prod.stock}}<br/>
          <form method="POST" autocomplete="off">
          {% csrf_token %}
          <input type="number" name="qty" value="{{pr.prodqty}}" placeholder="Enter The Number of Quantity" required><br/><br/>
          <input type="text" name="loc" value="{{pr.location}}" placeholder="Enter The Location" required><br/>
          <input type="hidden" name="idy" value="{{pr.id}}"><br/>

        </div>
        <div class="modal-footer">
          <button type="submit" name="updates" class="btn btn-default">Update</button>
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </form>
        </div>
      </div>
      
    </div>
  </div>

{% endfor %}
</tr>
</table>
</div>
</div>

{% endblock %}